name: Ruby Test and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  ImageOS: ubuntu20
jobs:
  build:
    runs-on: [self-hosted, Linux]
    services:
      postgres:
        image: postgres:14.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_DB: postgres
        ports:
          - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v1
        name: Checkout Repository
      #- name: Install postgres
      #  run: |
      #    apt-get update -y
      #    apt-get install -y libpq-dev postgresql-client
      #- name: Set up Ruby 3
      #  uses: ruby/setup-ruby@v1
      #  with:
      #    ruby-version: '3.0.2'
      #    bundler-cache: true
      #- name: Setup database
      #  run: bin/rails db:create db:migrate
      #- name: Run Tests
      #  run: |
      #    bundle exec rake test
      - name: Deploy to Heroku
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: "safe-earth-87186"
        if: job.status == 'success' && github.ref == 'refs/heads/main'
        run: |
          git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git origin/main:main